version: "3.8"

networks:
  agent_network:
    driver: bridge

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - agent_network

  agent:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: agent
    restart: always
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379
    networks:
      - agent_network
    depends_on:
      - redis
