version: "3.8"

networks:
  agent_network:
    driver: bridge

services:
  agent:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: agent
    restart: always
    ports:
      - "8000:8000"
    networks:
      - agent_network
